[package]
name = "clock"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
crossterm = "0.28.1"
serde = { version = "1.0.210", features = ["derive", "rc"] }
serde_json = "1.0.128"
serde_millis = "0.1.1"
